### PR TITLE
Cleanup and rewrite to make this importable into other projects

### PR DESCRIPTION
**Pull request by utkonos**
I have brought the code style mostly in line with PEP8 style guide.
This module now importable by other python code.
setup.py is updated to follow pypi standards - this module is ready for release on pypi and pip installation.
The command line is now cross-platform and uses argparse to provide arguments.
A number of other cleanups.

### CODE REVIEW

**Comment by austinbyers** [comment]
@utkonos one of the things I was going to do was to look at the official [yara grammar](https://github.com/VirusTotal/yara/blob/master/libyara/grammar.y) and make sure it's all supported.

You might also be able to leverage the yara test files to make sure we have full coverage.

I'm not sure if @8u1a is still active, but thanks for all your work on this. If we can't merge it here, we might be able to fork it elsewhere

**Comment by larsborn** [comment]
@austinbyers any news on this? Thought about forking this too. 
* Do you have a better way of contacting @8u1a about his thoughts on this?
* Are you still interested to fork? Just want to make sure to not duplicate any efforts!

@utkonos only took a quick look at your PR. Thanks a lot! Any interest on forking this project from your side?

@austinbyers @utkonos: Interested in teaming up on this?

**Comment by Taskr** [comment]
@larsborn Community-maintained fork of plyara at https://github.com/plyara/plyara

**Comment by utkonos** [comment]
Project moved to https://github.com/plyara/plyara

**Pull request closed without merging**
